name: Verify Keystore

on:
  workflow_dispatch: # Memungkinkan kamu menjalankan manual dari tab Actions

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

      - name: Verify Keystore Password and Alias
        run: |
          # Perintah ini akan mencoba melist isi keystore.
          # Jika password salah, perintah ini akan fail.
          keytool -list -v \
            -keystore release.keystore \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -alias "${{ secrets.KEY_ALIAS }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}"

          echo "✅ Keystore, Password, dan Alias VALID!"
